#  Лабораторна робота № 4
# Основи роботи з бібліотекою NumPy
# *Мета роботи: отримати базові знання та навички по роботі з бібліотекою NumPy*
# Уманський Андрій КН-221д

In [14]:
N = ord('A') % 15 + 1
print(N)

6


In [130]:
# import numpy as np

# array1 = np.array([[1,2,3],[4,5,6]], dtype ='float')

# np.zeros((3,5),dtype="int") # матриця нулів
# np.eye(5) # одинична матриця
# np.full((3,3),228) # матриця 3х5 де всі 228
# np.arange(0, 20, 2) 
# np.linspace(0, 1, 6) # поділ діапазону на 6 частин
# np.random.random((3, 3)) # rnd
# np.random.normal(0, 1, (3,3))
# np.random.randint(0, 10, (3,3))
# np.empty(6)
# x = np.array([1,2])
# y = np.diag(x)
# c = np.diag(y)
# #print(f"{y}\n\n{c}") # з 1вим в 2вим і навпаки (діагональ)
# np.array([1,2] * 5) #повторювання

# arr[:, ::2] = 1

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

# Завдання 1

In [1]:
# Завдання 1 
# Вправа 1
import numpy as np

def sup(n):
    x = [i+1 for i in range(n)]
    return x

def ex_1_1():
    n = int(input("Введіть значення n = "))
    x = np.array(sup(n))
    return np.diag(x)
#     print(np.diag(x),"\n\n")


def ex_1_2():
    n = int(input("Введіть значення n = "))
    x = sup(n)
    my_list = []
    for i in range(n):
        list1 = []
        for j in range(n):
            if i == j:
                list1.append(x[j])
            else:
                list1.append(0)
        my_list.append(list1)
    return my_list
#     for i in my_list:
#         print(i)

        

In [2]:
import time
start = time.time()
print(ex_1_1())
end = time.time() - start
print(f"time = {end}")

Введіть значення n = 4
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
time = 3.499243974685669


In [4]:
start = time.time()
for i in ex_1_2():
    print(i)
end = time.time() - start
print(f"time = {end}")

Введіть значення n = 4
[1, 0, 0, 0]
[0, 2, 0, 0]
[0, 0, 3, 0]
[0, 0, 0, 4]
time = 0.7737970352172852


In [53]:
# Завдання 1
# Вправа 3
import numpy as np

def ex_3_1():
    n=int(input("n = "))
    m=int(input("m = "))
    r=int(input("r = "))
    c=int(input("c = "))
    my_list=[]
    for i in range(n):
        list1=[]
        for j in range(m):
            if j%c==0 or i%r==0:
                list1.append(0)
            else:
                list1.append(1)
        my_list.append(list1)
    return my_list

def ex_3_2():
    n=int(input("n = "))
    m=int(input("m = "))
    r=int(input("r = "))
    c=int(input("c = "))
    array = np.ones((n,m))
    array[::r,:] = 0
    array[:,::c] = 0
    return array

In [54]:
for i in ex_3_1():
    print(i)

n = 5
m = 5
r = 2
c = 3
[0, 0, 0, 0, 0]
[0, 1, 1, 0, 1]
[0, 0, 0, 0, 0]
[0, 1, 1, 0, 1]
[0, 0, 0, 0, 0]


In [27]:
ex_3_2()

n = 5
m = 5
r = 2
c = 2


array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Задвання 1
# Вправа 6
import numpy as np
def ex_6_1():
    size = int(input("Введіть розмір масива = "))
    my_list=[]
    for i in range(size):
        x = int(input())
        if x==0:
            my_list.append(0)
        else:
            my_list.append(-1)
    return my_list

def ex_6_2():
    size = int(input("Введіть розмір масива = "))
    my_list=[]
    for i in range(size):
        my_list.append(int(input()))
    array = np.array(my_list)
    return np.where(array!=0,-1,array)
    #np.where()

In [6]:
import time
start = time.time()
print(ex_6_1())
end = time.time() - start
print(f"time = {end}")

Введіть розмір масива = 3
1
0
3
[-1, 0, -1]
time = 3.918700933456421


In [22]:
import time
start = time.time()
print(ex_6_2())
end = time.time() - start
print(f"time = {end}")

Введіть розмір масива = 2
2
2
[-1 -1]
1.3489902019500732


In [7]:
# Завдання 1
# Вправа 4
import numpy as np

def ex_4_1():
    n =int(input("n = "))
    m =int(input("m = "))
    my_list=[]
    for i in range(n):
        list1=[]
        for j in range(m):
            if i!=0:
                list1.append(0)
            else:
                list1.append(j)
        my_list.append(list1)
    return my_list

def ex_4_2():
    n = int(input("n = "))
    m = int(input("m = "))
    array = np.arange(0,n*m,1)
    array[array>m-1] = 0
    return array.reshape(n,m)

In [8]:
import time as t
start = t.time()
for i in ex_4_1():
    print(i)
end = t.time() - start
print(f"time = {end}")

n = 4
m = 4
[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
time = 2.274533748626709


In [22]:
import time as t
start = t.time()
print(ex_4_2())
end = t.time() - start
print(f"time = {end}")

n = 3
m = 3
[[0 1 2]
 [0 0 0]
 [0 0 0]]
time = 1.4717495441436768


In [10]:
# Завдання 1
# Вправа 10
import random as rnd
from math import sqrt
import numpy as np

def ex_10_1():
    n = int(input("n = "))
    m = int(input("m = "))
    my_list=[];up = 0
    for i in range(n):
        for j in range(m):
            my_list.append(round(rnd.random(),3)) 
            
    my_list_min = min(my_list)
    my_list_max = max(my_list)
    my_list_average = round((sum(my_list))/(n*m),3)
    for i in my_list:
        up += (i-my_list_average)**2
    my_list_disp = round(math.sqrt(up/(n*m)),3)
        
    return f"min = {my_list_min}\nmax = {my_list_max}\naverage = {my_list_average}\ndisp = {my_list_disp}"

def ex_10_2():
    n = int(input("n = "))
    m = int(input("m = "))
    array = np.random.random(size=(n,m))
    array = np.round(array,3)
    array_max = array.max()
    array_min = array.min()
    array_average = round(np.average(array),3)
    array_disp = round(np.std(array),3)
    return f"min = {array_min}\nmax = {array_max}\naverage = {array_average}\ndisp = {array_disp}"

In [151]:
import time
start = time.time()
print(ex_10_1())
end = time.time() - start
print(f"time = {end}")

n = 3
m = 3
min = 0.105
max = 0.967
average = 0.584
disp = 0.317
1.6249728202819824


In [11]:
import time
start = time.time()
print(ex_10_2())
end = time.time() - start
print(f"time = {end}")

n = 3
m = 3
min = 0.049
max = 0.914
average = 0.388
disp = 0.315
time = 0.9660851955413818


In [23]:
# Завдання 1
# Впарва 12
import numpy as np

def ex_12_1():
    n = int(input("n = "))
    my_list=[]
    for i in range(n):
        list1=[]
        for j in range(n):
            if i==0 or i==n-1 or j==0 or j==n-1:
                list1.append(0)
            else:
                list1.append(1)
        my_list.append(list1)
    return my_list

def ex_12_2():
    n = int(input())
    array = np.ones((n,n),dtype=float)
    array[0, :] = 0
    array[(n-1), :] = 0
    array[:, 0] = 0
    array[:, (n-1)] = 0
    return array

In [30]:
import time as tm
start = tm.time()
for i in ex_12_1():
    print(i)
end = tm.time() - start
print(end)

n = 5
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]
1.1903421878814697


In [31]:
import time as tm
start = tm.time()
print(ex_12_2())
end = tm.time() - start
print(end)

5
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
0.45606422424316406


In [168]:
# Завдання 1
# Вправа 15
import numpy as np

def ex_15_1():
    n = int(input())
    my_list=[]
    for i in range(n):
        list1=[]
        for j in range(n):
            if j%2:
                list1.append(1)
            else:
                list1.append(0)
        my_list.append(list1)
    return my_list

def ex_15_2():
    n = int(input())
#     arr = np.full((n,n), 1)
#     arr[:, ::2] = 0
#     return arr

    one = [i for i in range(n) if i%2]
    two = [i for i in range(n) if i%2==0]
    array = np.arange(1,(n*n)+1).reshape(n,n)
    array[: ,one] = 1
    array[: ,two] = 0
    return array

In [166]:
import time as tm
start = tm.time()
for i in ex_15_1():
    print(i)
end = tm.time() - start
print(end)

5
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
0.5119497776031494


In [169]:
import time as tm
start = tm.time()
print(ex_15_2())
end = tm.time() - start
print(end)

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
0.48491668701171875


In [15]:
# Завдання 1
# Вправа 17
import numpy as np

def ex_17_1():
    n = int(input())
    my_list=[]
    for i in range(0,n+1,1):
        my_list.append(i)
    
    for i in range(n+1):
        if my_list[i] < n/2 or my_list[i] > (3*n)/4:
            my_list[i] = -my_list[i]

    return my_list

def ex_17_2():
    n = int(input())
    array = np.arange(0,n+1,1)
    array[(array < n/2) | (array > (3*n)/4)] *= -1
    return array

In [16]:
ex_17_1()

10


[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]

In [14]:
ex_17_2()

10


array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

In [62]:
# Завдання 1
# Вправа 18
import random as rnd
import numpy as np

def ex_18_1():
    n = int(input())
    rnd_list = [rnd.randint(0,99) for el in range(n)]
    
    dict_ = {}
    for i in rnd_list:
        if i in dict_:
            dict_[i] += 1
        else:
            dict_[i] = 1
            
    for k,v in dict_.items():
        print(f"{k} : {v}")
    
    counter = 0
    for i in dict_.values():
        if i==1:
            counter+=1
    return counter

def ex_18_2():
    n = int(input())
    array = np.random.randint(0,99,size=(n))
    uniq = len(np.unique(array))
    return array, uniq

In [63]:
#### import time as t
start = t.time()
print(ex_18_1())
end = t.time() - start
print(end)

15
7 : 1
80 : 1
5 : 1
15 : 1
57 : 1
25 : 1
26 : 2
24 : 1
59 : 1
47 : 1
21 : 1
6 : 1
51 : 1
88 : 1
13
0.8607661724090576


In [29]:
import time as t
start = t.time()
print(ex_18_2())
end = t.time() - start
print(end)

10
(array([83, 28, 74, 74, 43,  7, 40, 97, 70, 91]), 9)
1.3084979057312012


# Завдання 2

In [2]:
import numpy as np
a = np.array([[1,5,3,-4],[3,1,-2,0],[5,-7,0,10],[0,3,-5,0]])
b = np.array([20,9,-9,1])

determ = np.linalg.det(a)

a_1 = (np.column_stack((b, a[:, 1:])))
a_2 = (np.column_stack((a[:, 0],b, a[:, 2:])))
a_3 = (np.column_stack((a[:, :2],b, a[:, 3:])))
a_4 = (np.column_stack((a[:, :3],b, a[:, 4:])))

x_1 = np.linalg.det(a_1)/determ 
x_2 = np.linalg.det(a_2)/determ
x_3 = np.linalg.det(a_3)/determ
x_4 = np.linalg.det(a_4)/determ

kramer_answer = np.array([x_1,x_2,x_3,x_4])

a_answer = np.dot(a, kramer_answer)
b_answer = np.dot(np.linalg.inv(a),b)
c_answer = np.linalg.solve(a,b)

print(f"{a} \n\n\ndeterm = {determ.round(2)}\n")
print(f"{a_1}\n\n{a_2}\n\n{a_3}\n\n{a_4}\n\n")
print(f"Kramer = {kramer_answer}")

print(np.allclose(a_answer, b))
print(np.allclose(b_answer, kramer_answer))
print(np.allclose(c_answer, kramer_answer))

[[ 1  5  3 -4]
 [ 3  1 -2  0]
 [ 5 -7  0 10]
 [ 0  3 -5  0]] 


determ = -630.0

[[20  5  3 -4]
 [ 9  1 -2  0]
 [-9 -7  0 10]
 [ 1  3 -5  0]]

[[ 1 20  3 -4]
 [ 3  9 -2  0]
 [ 5 -9  0 10]
 [ 0  1 -5  0]]

[[ 1  5 20 -4]
 [ 3  1  9  0]
 [ 5 -7 -9 10]
 [ 0  3  1  0]]

[[ 1  5  3 20]
 [ 3  1 -2  9]
 [ 5 -7  0 -9]
 [ 0  3 -5  1]]


Kramer = [ 3.  2.  1. -1.]
True
True
True


# Завдання 3

In [17]:
import numpy as np
A = np.array([[5,2,0],[10,4,1],[7,3,2]])
B = np.array([[3,6,-1],[-1,-2,0],[2,1,3]])
print(f"A:\n{A}\n\nB:\n{B}\n\n")
end = (A - (B**2)) * (2*A+B)
print(end)

A:
[[ 5  2  0]
 [10  4  1]
 [ 7  3  2]]

B:
[[ 3  6 -1]
 [-1 -2  0]
 [ 2  1  3]]


[[ -52 -340    1]
 [ 171    0    2]
 [  48   14  -49]]


https://github.com/TheRufio/lab4_python